FROM node:20-alpine

#working directory
WORKDIR /app

#Copy package.json file 
COPY package*.json ./

#install dependencies
RUN npm install

#Copy rest of code 
COPY . .

#Expose app port
EXPOSE 8000

#Start app
CMD ["npm", "start"]